ALGORITHM_VALUE_INTEGER = "integer"
ALGORITHM_VALUE_2D_POINT = "2d_point"
ALGORITHM_VALUE_3D_POINT = "3d_point"

ALGORITHM_RENDER_TRIANGLES = "triangles"
ALGORITHM_RENDER_LINES = "lines"
ALGORITHM_RENDER_POINTS = "points"

VALID_ALGORITHM_VALUE_TYPES = (
    ALGORITHM_VALUE_INTEGER,
    ALGORITHM_VALUE_2D_POINT,
    ALGORITHM_VALUE_3D_POINT
)

VALID_ALGORITHM_RENDER_TYPES = (
    ALGORITHM_RENDER_TRIANGLES,
    ALGORITHM_RENDER_LINES,
    ALGORITHM_RENDER_POINTS
)
